config/routes.rb
PhotogurAttempt3::Application.routes.draw do

  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base

    scope :newest_first, -> {order("created_at desc")}
    scope :newest_two, -> {newest_first.limit(2)}
    scope :created_before, -> (time) {where("created_at < ?", time)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController


    def index

        @images = Image.newest_two

    end 

    def new

        @image = Image.new

    end 

    def create

        if Image.create(allow_params)
            redirect_to images_path
        else
            render :new 
        end 

    end


    def show

        @image=Image.where(id: params[:id]).first

    end 


    def edit

        @image=Image.where(id: params[:id]).first

    end

    def update

        @image=Image.where(id: params[:id]).first

        if @image.update_attributes(allow_params)

            redirect_to image_path(@image)
        else 
            render :edit

        end 

    end 

    def destroy

        Image.where(id: params[:id]).first.delete

        redirect_to images_path

    end 

    private 

    def allow_params

        params.require(:image).permit(:title,:url)

    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<p>Edit your image below</p>

<%= form_for @image do |f| %>

    <p><%= f.label "title", "TITLE" %></p>
    <%= f.text_field "title" %>

    <p><%= f.label "url", "URL" %></p>
    <%= f.text_field "url" %>

    <%= f.submit "Update Info" %>

<% end %>


<p><%= image_tag(@image.url) %></p>

app/views/images/index.html.erb
<p>Here are all the image:</p>

<%= link_to "Add a new image", new_image_path %>

<% @images.each do |image| %>

    <p><%= image.title %></p>
    <p><%= link_to image_tag(image.url), image_path(image) %></p>

<% end %>

app/views/images/new.html.erb
<p>Add your image below:</p>

<%= form_for @image do |f| %>

    <p><%= f.label "title" %></p>
    <p><%= f.text_field "title" %></p>

    <p><%= f.label "url" %></p>
    <p><%= f.text_field "url" %></p>

    <p><%= f.submit "Save" %></p>

<% end %>

app/views/images/show.html.erb
<p>Here's the image:</p>
<%= link_to "Back", images_path %>
<%= link_to "Delete", @image, :method => "delete" %>
<p><%= @image.title %></p>
<%= link_to image_tag(@image.url), edit_image_path(@image) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotogurAttempt3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>